In [19]:
from scipy.signal import correlate, convolve
import numpy as np
a=np.array([[2,0,5,0,3],[0,1,0,3,2],[4,0,0,1,2],[1,0,3,0,1]])
filt=np.array([[0,0,1],[0,0,0],[-1,0,0]])
print(a)
print(filt)


[[2 0 5 0 3]
 [0 1 0 3 2]
 [4 0 0 1 2]
 [1 0 3 0 1]]
[[ 0  0  1]
 [ 0  0  0]
 [-1  0  0]]


In [20]:
print(correlate(in1=a,in2=filt,mode='valid'))
print(convolve(a,filt ,mode='valid'))


[[ 1  0  3]
 [-1  3 -1]]
[[-1  0 -3]
 [ 1 -3  1]]


In [23]:
filt=np.array([[1/9,1/9,1/9],[1/9,1/9,1/9],[1/9,1/9,1/9]])
print(convolve(a,filt,'same'))


[[0.33333333 0.88888889 1.         1.44444444 0.88888889]
 [0.77777778 1.33333333 1.11111111 1.77777778 1.22222222]
 [0.66666667 1.         0.88888889 1.33333333 1.        ]
 [0.55555556 0.88888889 0.44444444 0.77777778 0.44444444]]
